;interface.au3

Global $Main = GUICreate("Custom Settings",684,375,-1,-1,-1,-1)
Global $tab = GUICtrlCreatetab(218,10,389,358,-1,-1)
GuiCtrlSetState(-1,2048)
GUICtrlCreateTabItem("Fast Mode")
GUICtrlCreateTabItem("Avoidance")
GUICtrlCreateTabItem("")
_GUICtrlTab_SetCurFocus($tab,-1)
GUISwitch($Main,_GUICtrlTab_SetCurFocus($tab,1)&GUICtrlRead ($tab, 1))
Global $LstViewAvoidance = GUICtrlCreatelistview("",228,40,362,318,-1,$WS_EX_CLIENTEDGE)
_GUICtrlListView_InsertColumn($LstViewAvoidance, 0, "Paramètre", 260)
_GUICtrlListView_InsertColumn($LstViewAvoidance, 1, "Valeur", 78)
GUICtrlCreateTabItem("")
Global $BtnLog = GUICtrlCreateButton("Log",616,328,57,30,-1,-1)
Global $BtnLoad = GUICtrlCreateButton("Load",616,40,57,30,-1,-1)
Global $BrnSave = GUICtrlCreateButton("Save",616,74,57,30,-1,-1)
GUISwitch($Main,_GUICtrlTab_SetCurFocus($tab,0)&GUICtrlRead ($tab, 1))
Global $LstViewFastMode = GUICtrlCreatelistview("",228,40,362,318,-1,$WS_EX_CLIENTEDGE)
_GUICtrlListView_InsertColumn($LstViewFastMode, 0, "Paramètre", 300)
_GUICtrlListView_InsertColumn($LstViewFastMode, 1, "Valeur", 58)
GUICtrlCreateTabItem("")
Global $LstFastMode = GUICtrlCreatelist("",10,9,200,357,-1,$WS_EX_CLIENTEDGE)
_GUICtrlTab_SetCurFocus($tab,0)